services:
  postgres:
    image: postgres:16
    container_name: dagster_dbt_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dagster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dagster"]
      interval: 10s
      timeout: 5s
      retries: 5


  localstack:
    image: localstack/localstack-pro
    container_name: dagster_dbt_localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
     - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN} # env var defined with token in .env
     - DEBUG=${DEBUG:-0}
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"


volumes:
  postgres_data:
  localstack_data:
